### ISSUE TITLE
Handle escape directive for Dockerfiles

### ISSUE THREAD

**Issue by schribl** [containerbuildsystem/dockerfile-parse#109]
**Problem description**
For Windows Dockerfiles it can often be beneficial to use the `escape` directive ([Documentation](https://docs.docker.com/engine/reference/builder/#escape)) as Windows uses `\` for paths. The current parser implementation does not handle this directive and reports errors on specific operations:

```
In [11]: df.context_structure
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-11-90b26318ceeb> in <module>
----> 1 df.context_structure

c:\python38\lib\site-packages\dockerfile_parse\parser.py in context_structure(self)
    818
    819             if instruction_type in ('ARG', 'ENV', 'LABEL'):
--> 820                 values = get_key_val_dictionary(
    821                     instruction_value=instr['value'],
    822                     env_replace=instruction_type != 'ARG' and self.env_replace,

c:\python38\lib\site-packages\dockerfile_parse\util.py in get_key_val_dictionary(instruction_value, env_replace, args, envs)
    256     args = args or {}
    257     envs = envs or {}
--> 258     return dict(extract_key_values(instruction_value=instruction_value,
    259                                    env_replace=env_replace,
    260                                    args=args, envs=envs))

c:\python38\lib\site-packages\dockerfile_parse\util.py in extract_key_values(env_replace, args, envs, instruction_value)
    244         for k_v in words:
    245             if '=' not in k_v:
--> 246                 raise ValueError('Syntax error - can\'t find = in "{word}". '
    247                                  'Must be of the form: name=value'
    248                                  .format(word=k_v))

ValueError: Syntax error - can't find = in "`". Must be of the form: name=value
```

**Workaround & Solution**
A short term workaround can be to avoid this feature. And for the parser the docker directives have to be on the first line of the file so it is valid for the whole file and can be found/detected quite good. So from what I see it might be one change to detect this directive and one to change the [regex](https://github.com/containerbuildsystem/dockerfile-parse/blob/master/dockerfile_parse/parser.py#L266) based on this detection.

**Comment by MartinBasti** [comment]
Thank you for reporting this issue!

Are you willing to help us addressing this issue by providing a PR?

**Comment by schribl** [comment]
@MartinBasti Yes I am willing to do a PR for this. I do not know when I will have the time to do so but I hope until end of next week.
