### ISSUE TITLE
dockerfile-parse creates a Dockerfile file

### ISSUE THREAD

**Issue by MartinThoma** [containerbuildsystem/dockerfile-parse#113]
When I run

```
from dockerfile_parse import DockerfileParser

dfp = DockerfileParser()
dfp.content = """\
From  base
LABEL foo="bar baz"
USER  me"""
```

it creates a `Dockerfile` locally. This is unexpected. Is it possible to not do that?

**Comment by MartinBasti** [comment]
Not in the current code. It'd require a serious refactor.

You can specify path to tempdir in init to avoid issues with creating local Dockerfiles

**Comment by twaugh** [comment]
IMHO the docstring for `DockerfileParser.__init__` ought to be updated to reflect how the code actually works, in that it uses the current working directory by default.

To change this behaviour, you can pass in a temporary directory for `path`, or an `io.BytesIO` object or whatever for `fileobj`.

**Comment by tkdchen** [comment]
Ideally, all the operations could be in-memory by default, and write to a file with an explicit method call like `write`, or the `fileobj` is provided to `__init__`.

BTW, `stream` would be a better name than `fileobj` to keep consistent with other functions and methods in the Python standard library.
