### ISSUE TITLE
ARG's are not inherited from a parent stage - only the last stage is considered

### ISSUE THREAD

**Issue by Adam-Ant** [containerbuildsystem/dockerfile-parse#116]
When using global ARG's outside of a FROM line (for instance, to make them available to multiple stages), only the last stage is used to generate the arguments property.

For example, this Dockerfile:
```Dockerfile
ARG GLOBALARG1=foo
ARG GLOBALARG2=bar

FROM python
ARG GLOBALARG1
RUN echo $GLOBALARG1 $GLOBALARG2

FROM python
ARG GLOABLARG2
RUN echo $GLOBALARG2
```

With this sample script:
```python
from pprint import pprint
from dockerfile_parse import DockerfileParser

dfp = DockerfileParser()

f = open("Dockerfile", "r")
dfp.content = f.read()

pprint(dfp.args)
```

returns `{'GLOABLARG2': ''}`, despite the fact that GLOBALARG2 should have inherited from the parent, and its entirely missing GLOBALARG1.

The library successfully detects this is a multistage build, but I can't seem to find a way to present the global arguments, or any arguments from a stage other than the last - as well as arguments not being inherited correctly

**Comment by MartinBasti** [comment]
You have typo in Dockerfile
```diff
  FROM python
- ARG GLOABLARG2
+ ARG GLOBALARG2
  RUN echo $GLOBALARG2
```

It prints correct `GLOBALARG2`
```
>>> pprint(dfp.args)                                                                                               
{'GLOBALARG2': 'bar'}
```

dockerfile-parse intentionally returns only values related to the latest stage

**Comment by MartinBasti** [comment]
Also from docs https://docs.docker.com/engine/reference/builder/#understand-how-arg-and-from-interact

> An ARG declared before a FROM is outside of a build stage, so it can’t be used in any instruction after a FROM. To use the default value of an ARG declared before the first FROM use an ARG instruction without a value inside of a build stage

Global ARGs are not available in the stage if there is no empty ARG declaration within stage.

IMO dockerfile-parse works as expected

**Comment by frebib** [comment]
Whilst it may be working as intended, we have a legitimate use-case for wanting to set values outside of the last block. Would you accept a PR that keeps the current behaviour, but allows the user to override it with a kwarg?

**Comment by MartinBasti** [comment]
Can you describe it more? What do you mean by override?

**Comment by frebib** [comment]
Sure. We have something akin to the following
```
ARG NAME=somevalue
ARG ANOTHER="another value"

FROM alpine

ARG NAME
ARG ANOTHER

RUN ..

FROM scratch

ARG NAME
```
`NAME` is pulled into both stages, but `ANOTHER` is not. We'd like to be able to set the value of `ANOTHER` (on line 2) but with the current logic it's not possible. In fact it's explicitly disallowed: https://github.com/containerbuildsystem/dockerfile-parse/blob/169a7ff5f56d93fc3d5d2ab4320edbf31ed94099/dockerfile_parse/parser.py#L628

**Comment by MartinBasti** [comment]
Oh, so you want to be able to modify ARG global definitions before the first FROM?

That sounds good to me

**Comment by MartinBasti** [comment]
I got broader agreement that this is a good idea, so I have opened 2 issues for that:

- https://github.com/containerbuildsystem/dockerfile-parse/issues/117
- https://github.com/containerbuildsystem/dockerfile-parse/issues/118

Contributions are welcome
