### ISSUE TITLE
make dockerfile-parse an RPM available on src.fedoraproject.org/projects/rpms/

### ISSUE THREAD

**Issue by JamesKunstle** [containerbuildsystem/dockerfile-parse#121]
I'm with the RHEL Compose team. This project would be very helpful for working with containers in (fedpkg/rhpkg/centpkg), but we would need it to be mirrored as an RPM available at src.fedoraproject.org/projects/rpms/.

I'm going to follow this process generally: https://blog.jwf.io/2017/11/first-rpm-package-fedora/

I'm adding this issue because I wanted to make sure product owners are aware I'm working on this. I would appreciate any experience anyone has to contribute to this process.

**Comment by lachmanfrantisek** [comment]
Isn't `dockerfile-parse` already packaged in Fedora?

https://src.fedoraproject.org/rpms/python-dockerfile-parse (Just a usual name change for `Python` packages.)

**Comment by athos-ribeiro** [comment]
That is right.

dockerfile-parse is packaged in Fedora as `python-dockerfile-parse`. The binary package is `python3-dockerfile-parse`

**Comment by JamesKunstle** [comment]
I'm unsure how I missed this but in either case, this is more than perfect, thank you!

**Comment by MartinBasti** [comment]
For EPEL7 and 8 can you reach fedora maintainer?

For eng-rhel9 it's RH internal and shouldn't be asked here, I opened RH tracker for you.

Closing issue as this is not an upstream issue
