### ISSUE TITLE
Base image is incorrect when FROM statement has --platform

### ISSUE THREAD

**Issue by rodneyxr** [containerbuildsystem/dockerfile-parse#124]
From the [docker docs](https://docs.docker.com/engine/reference/builder/#from) it says Dockerfile supports `--platform=<platform>` however when we try to reference the baseimage property of the parser, it reports the base image as the `--platform=<platform>` string.

Using the following Dockerfile:
```dockerfile
FROM --platform=linux/amd64 docker.io/library/centos:latest
```

And using the following code:
```python
from dockerfile_parse import DockerfileParser

parser = DockerfileParser(fileobj=containerfile)
print(parser.baseimage)
```

Here is my result
```
--platform=linux/amd64
```

**Comment by ElijahAhianyo** [comment]
Hi, can I take this up?

**Comment by MartinBasti** [comment]
yup, sure :)
