### ISSUE TITLE
Make readme render on PyPI

### ISSUE THREAD

**Issue by twm** [containerbuildsystem/dockerfile-parse#72]
The package lacks long_description metadata so it doesn't show anything on PyPI:

![image](https://user-images.githubusercontent.com/43662/50714214-adae5680-102c-11e9-9502-4951c0bbaa4b.png)

[StackOverflow](https://stackoverflow.com/questions/26737222/pypi-description-markdown-doesnt-work) describes how to fix this.

(Thanks for this library!)

**Comment by rcerven** [comment]
contribution is welcome

**Comment by twm** [comment]
I was settling down to do this but it looks like #75 beat me to it, but... it was closed instead of merged?
