### ISSUE TITLE
Keeping comments in the parsed result 

### ISSUE THREAD

**Issue by sebpiq-kialo** [containerbuildsystem/dockerfile-parse#77]
For now, comments are simply stripped from the output, would be great if they could be kept, as they are sometimes important for the parsing of the file. 2 use-cases : 

- Parser directives : https://docs.docker.com/engine/reference/builder/#parser-directives
- Implementing custom directives

I will work on a pull-request to add this, let me know if that's a big no-no, then I won't bother :)

**Comment by twaugh** [comment]
That would be great. Thank you!

**Comment by sebpiq** [comment]
Pull request : https://github.com/DBuildService/dockerfile-parse/pull/78

**Comment by MartinBasti** [comment]
Fixed in #78
